# Site settings
title: Jenny Chan
email: jenny.chan@bankofengland.co.uk
#description: > # this means to ignore newlines until "baseurl:"
#  Research Economist at the Bank of England.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jenncha.github.io" # the base hostname & protocol for your site
#twitter_username: jc
#github_username:  jc
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
